<?php
require_once __DIR__ . '/../includes/auth.php';
require_roles(['System Administrator','Regional Training Administrator','Approving Officer']);
$_SESSION['csrf_token'] ??= bin2hex(random_bytes(32));

$pendingStmt = $pdo->query("SELECT c.*,e.employee_no,e.email,CONCAT(e.first_name,' ',e.last_name) employee_name,COALESCE(c.certificate_type,t.title,'Training Certificate') training_title FROM certificates c JOIN employees e ON e.id=c.employee_id LEFT JOIN trainings t ON t.id=c.training_id WHERE c.status='PENDING' ORDER BY c.created_at ASC");
$pendingRequests = $pendingStmt->fetchAll();
$sentCertificates = $pdo->query("SELECT c.*,CONCAT(e.first_name,' ',e.last_name) employee_name,e.email,COALESCE(c.certificate_type,t.title,'Training Certificate') training_title FROM certificates c JOIN employees e ON e.id=c.employee_id LEFT JOIN trainings t ON t.id=c.training_id WHERE c.status<>'PENDING' AND c.email_sent_at IS NOT NULL ORDER BY c.email_sent_at DESC")->fetchAll();
$page_title = 'Certifications';
require __DIR__ . '/../includes/header.php';
?>
<div class="dashboard-heading"><div><span class="dashboard-eyebrow">CERTIFICATION MANAGEMENT</span><h1>Certifications and Requests</h1><p>Review employee requests, send certificates, and track successful email delivery.</p></div><span class="heading-icon"><?= $portalIcon('certificate') ?></span></div>
<?php if (($_GET['email'] ?? '') === 'sent'): ?><div class="notice success" role="status">Email sent successfully. The certificate image was delivered to the employee’s email address and moved to Sent Certificates.</div><?php elseif (($_GET['email'] ?? '') === 'already_sent'): ?><div class="notice success" role="status">This certificate email has already been sent. It is listed under Sent Certificates and cannot be sent again.</div><?php elseif (($_GET['email'] ?? '') === 'failed'): ?><div class="notice error" role="alert">The certificate was approved, but its email could not be sent. Check the SMTP configuration. It is not recorded under Sent Certificates.</div><?php endif; ?>

<section class="panel dashboard-panel"><div class="panel-heading"><span class="panel-icon"><?= $portalIcon('dashboard') ?></span><div><h2>Pending Employee Requests <span class="request-count"><?= count($pendingRequests) ?></span></h2><p>Review requests within five working days (Monday through Thursday; Friday through Sunday are excluded).</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Request</th><th>Employee</th><th>Training / Certificate Type</th><th>Submitted</th><th>Review target</th><th>Action</th></tr></thead><tbody>
<?php foreach ($pendingRequests as $certificate): $reviewClock = certificate_review_clock($certificate['created_at']); ?><tr><td><?= htmlspecialchars($certificate['certificate_no']) ?></td><td><?= htmlspecialchars($certificate['employee_no'] . ' · ' . $certificate['employee_name']) ?><br><span class="small"><?= htmlspecialchars($certificate['email'] ?? '') ?></span></td><td><?= htmlspecialchars($certificate['training_title']) ?></td><td><?= htmlspecialchars($certificate['created_at']) ?></td><td><?php if ($reviewClock['overdue'] > 0): ?><span class="sla-badge overdue">Overdue <?= $reviewClock['overdue'] ?> workday(s)</span><?php elseif ($reviewClock['remaining'] === 0): ?><span class="sla-badge due">Due today</span><?php else: ?><span class="sla-badge on-track"><?= $reviewClock['remaining'] ?> workday(s) left</span><?php endif; ?></td><td><a class="btn" href="certificate_approve.php?id=<?= (int)$certificate['id'] ?>">Review / Upload Image</a></td></tr><?php endforeach; ?>
<?php if (!$pendingRequests): ?><tr><td colspan="6">No certificate requests are waiting for review.</td></tr><?php endif; ?>
</tbody></table></div></section>

<section class="panel dashboard-panel"><div class="panel-heading"><span class="panel-icon"><?= $portalIcon('certificate') ?></span><div><h2>Sent Certificates <span class="request-count"><?= count($sentCertificates) ?></span></h2><p>Successful email deliveries are recorded here. These certificates cannot be sent again.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Certificate No.</th><th>Employee</th><th>Training / Certificate Type</th><th>Email sent</th><th>Valid Until</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($sentCertificates as $certificate): ?><tr><td><?= htmlspecialchars($certificate['certificate_no']) ?></td><td><?= htmlspecialchars($certificate['employee_name']) ?><br><span class="small"><?= htmlspecialchars($certificate['email']) ?></span></td><td><?= htmlspecialchars($certificate['training_title']) ?></td><td><span class="sla-badge on-track">Sent</span><br><span class="small"><?= htmlspecialchars($certificate['email_sent_at']) ?></span></td><td><?= htmlspecialchars($certificate['valid_until'] ?? '-') ?></td><td><a class="btn secondary" href="<?= BASE_URL ?>/public/verify.php?token=<?= urlencode($certificate['qr_token']) ?>">Verify</a></td></tr><?php endforeach; ?>
<?php if (!$sentCertificates): ?><tr><td colspan="6">No certificate emails have been sent yet.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php require __DIR__ . '/../includes/footer.php'; ?>
